"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Rahul Rathan and Nawal Osama, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:rr53829
UT EID 2:no4535
"""


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start+1, nums, target)


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if nums[start] == 6:
        return group_sum(start + 1, nums, target - nums[start])
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start+1, nums, target)



# TODO: Modify this function. You may delete this comment when you are done.
def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if group_sum(start + 2, nums, target - nums[start]):
        return True
    return group_sum(start+1, nums, target)


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 is 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if nums[start] % 5 == 0:
        if start + 1 < len(nums) and nums[start + 1] == 1:
            return group_sum(start + 2, nums, target - nums[start])
        else:
            return group_sum(start + 1, nums, target - nums[start])
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start+1, nums, target)


# TODO: Modify this function. You may delete this comment when you are done.
def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    count = 1
    while start + count < len(nums) and nums[start] == nums[start + count]:
        count += 1
    v = nums[start] * count
    if group_sum(start + count, nums, target - v):
        return True
    return group_sum(start + count, nums, target)


# TODO: Modify this function
def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    tsum = sum(nums)
    if tsum % 2 != 0:
        return False
    target = tsum // 2 

    def can_partition(nums, target):
        if target == 0:
            return True
        if target < 0 or not nums:
            return False

        return (can_partition(nums[1:], target - nums[0]) or can_partition(nums[1:], target))  
    
    return can_partition(nums, target)
    


# TODO: Modify this function. You may delete this comment when you are done.
def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    tsum = sum(nums)
    if tsum % 2 != 1:
        return False

    def can_partition(nums, odd_sum, ten_sum):
          if not nums:
            return (odd_sum % 2 != 0) and (ten_sum % 10 == 0)
          current = nums[0]
          include_odd = can_partition(nums[1:], odd_sum + current, ten_sum)
          include_ten = can_partition(nums[1:], odd_sum, ten_sum + current)
          exclude = can_partition(nums[1:], odd_sum, ten_sum)  
          return include_odd or include_ten or exclude
    
    return can_partition(nums, 0,0)


# TODO: Modify this function. You may delete this comment when you are done.
def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    group_5 = []
    for num in nums:
        if num%5 == 0:
            group_5.append(num)
    group_3 = []
    for num in nums:
        if num%3 ==0 and num%5 != 0:
            group_3.append(num)
    sum_5 = sum(group_5)
    sum_3 = sum(group_3)

    remaining = []
    for num in nums:
        if num%5 != 0 and num%3 != 0:
            remaining.append(num)

    target = (sum_5 + sum_3 + sum(remaining)) // 2

    def can_split(remaining, current_sum):
        if current_sum == target:
            return True
        if current_sum > target or not remaining:
            return False
        return (can_split(remaining[1:], current_sum + remaining[0]) or
                can_split(remaining[1:], current_sum))

    return can_split(remaining, 0)

